version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=Europe/Amsterdam
      - ServerIP=192.168.2.15
    volumes:
       - '/mnt/Raspberry/pihole/etc-pihole/:/etc/pihole/'
       - '/mnt/Raspberry/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    privileged: true
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    privileged: true
    environment:
        - TZ=Europe/Amsterdam
        - PUID=1000
        - PGID=1000
        - MEM_LIMIT=512M
    volumes:
        - /mnt/Raspberry/unificonfig:/config
    ports:
        - 3478:3478/udp
        - 10001:10001/udp
        - 8080:8080
        - 8443:8443
        - 1900:1900/udp 
        - 8843:8843
        - 8880:8880 
        - 6789:6789 
        - 5514:5514 
    restart: unless-stopped
  unifi-poller:
    restart: unless-stopped
    image: golift/unifi-poller:${POLLER_TAG}
    ports:
        - 9130:9130
    environment:
        - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
        - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
        - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}